export const KEYWORD_SEARCH_START = 'KEYWORD_SEARCH_START'
export const KEYWORD_SEARCH_SUCCESS = 'KEYWORD_SEARCH_SUCCESS'
export const KEYWORD_SEARCH_FAIL = 'KEYWORD_SEARCH_FAIL'

export const JOB_SEARCH_START = 'JOB_SEARCH_START'
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS'
export const JOB_SEARCH_FAIL = 'JOB_SEARCH_FAIL'