export const KEYWORD_SEARCH_START = 'KEYWORD_SEARCH_START';
export const KEYWORD_SEARCH_SUCCESS = 'KEYWORD_SEARCH_SUCCESS';
export const KEYWORD_SEARCH_FAIL = 'KEYWORD_SEARCH_FAIL';

export const JOB_SEARCH_START = 'JOB_SEARCH_START';
export const JOB_SEARCH_CACHE_FAIL = 'JOB_SEARCH_CACHE_FAIL';
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS';
export const JOB_SEARCH_FAIL = 'JOB_SEARCH_FAIL';

export const COOCCURRENCE_SEARCH_START = 'COOCCURRENCE_SEARCH_START';
export const COOCCURRENCE_SEARCH_SUCCESS = 'COOCCURRENCE_SEARCH_SUCCESS';
export const COOCCURRENCE_SEARCH_FAIL = 'COOCCURRENCE_SEARCH_FAIL';

export const WS_MESSAGE = 'WS_MESSAGE';


export const CHART_UPDATE = 'CHART_UPDATE';
export const JOB_KEYWORD_UPDATE = 'JOB_KEYWORD_UPDATE';
export const CHART_UPDATE_FAIL = 'CHART_UPDATE_FAIL';