export const KEYWORD_SEARCH_START = 'KEYWORD_SEARCH_START';
export const KEYWORD_SEARCH_SUCCESS = 'KEYWORD_SEARCH_SUCCESS';
export const KEYWORD_SEARCH_FAIL = 'KEYWORD_SEARCH_FAIL';

export const JOB_SEARCH_START = 'JOB_SEARCH_START';
export const JOB_SEARCH_CACHE_FAIL = 'JOB_SEARCH_CACHE_FAIL';
export const JOB_SEARCH_SUCCESS = 'JOB_SEARCH_SUCCESS';
export const JOB_SEARCH_FAIL = 'JOB_SEARCH_FAIL';

export const SEE_MORE = 'SEE_MORE';
export const SEE_LESS = 'SEE_LESS';

export const CHART_CLEAR = 'CHART_CLEAR';
export const CHART_UPDATE = 'CHART_UPDATE';
export const JOB_KEYWORD_UPDATE = 'JOB_KEYWORD_UPDATE';

export const SOCKETS_CONNECTING = 'SOCKETS_CONNECTING';
export const SOCKETS_CONNECT_AND_SEND = 'SOCKETS_CONNECT';
export const SOCKETS_CONNECTED = 'SOCKETS_CONNECTED';
export const SOCKETS_DISCONNECTING = 'SOCKETS_DISCONNECTING';
export const SOCKETS_DISCONNECT = 'SOCKETS_DISCONNECT';
export const SOCKETS_DISCONNECTED = 'SOCKETS_DISCONNECTED';
export const SOCKETS_MESSAGE_SENDING = 'SOCKETS_MESSAGE_SENDING';
export const SOCKETS_MESSAGE_SEND = 'SOCKETS_MESSAGE_SEND';
export const SOCKETS_MESSAGE_RECEIVING = 'SOCKETS_MESSAGE_RECEIVING';
export const SOCKETS_MESSAGE_RECEIVE = 'SOCKETS_MESSAGE_RECEIVE';
export const SOCKETS_MESSAGE_SUBSCRIBE = 'SOCKETS_MESSAGE_SUBSCRIBE';