export const serverUrl = "http://127.0.0.1:8888";
export const wsUrl = serverUrl + "/keyword-ws";
export const jobDescriptionApiUrl = serverUrl + "/job-list";
export const correlateWordReqUrl = serverUrl + "/most-correlated-words";
export const i18nTextUrl = serverUrl + "/internationalization/i18n-content";
export const mainPageUrl = "/alaitp-frontend";
export const searchResUrl = mainPageUrl + "/keywords";
export const personalPageUrl = mainPageUrl + "/personal-page";
export const contactUrl = personalPageUrl;